import Vue from 'vue'
import { Button, Tabbar, TabbarItem, NavBar, Form, Field, Toast, Search, Swipe, SwipeItem, Grid, GridItem, Icon, Sidebar, SidebarItem, TreeSelect, Rate, ActionSheet, Stepper, Dialog, Badge, Checkbox, Empty } from 'vant'

Vue.use(Button)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Form)
Vue.use(Field)
Vue.use(Toast)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Icon)
Vue.use(Sidebar)
Vue.use(SidebarItem)
Vue.use(TreeSelect)
Vue.use(Rate)
Vue.use(ActionSheet)
Vue.use(Stepper)
Vue.use(Dialog)
Vue.use(Badge)
Vue.use(Checkbox)
Vue.use(Empty)
